#############################################################################
# Makefile for building: Phase_Shifting
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  Phase_Shifting.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile Phase_Shifting.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/ros/kinetic/include/opencv-3.3.1-dev -Iinclude -Isrc -isystem /usr/include/flycapture -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Phase_Shifting1.0.0
DISTDIR = /home/chao/phase_shifting/.tmp/Phase_Shifting1.0.0
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS) -L/opt/ros/kinetic/lib/x86_64-linux-gnu -lopencv_core3 -lopencv_imgcodecs3 -lopencv_highgui3 -lopencv_imgproc3 -lopencv_calib3d3 -lflycapture -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/camera.cpp \
		src/patterns.cpp \
		src/phases.cpp \
		src/tools.cpp \
		src/preprocessing.cpp 
OBJECTS       = main.o \
		camera.o \
		patterns.o \
		phases.o \
		tools.o \
		preprocessing.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Phase_Shifting.pro include/camera.h \
		include/patterns.h \
		include/phases.h \
		include/tools.h \
		include/preprocessing.h src/main.cpp \
		src/camera.cpp \
		src/patterns.cpp \
		src/phases.cpp \
		src/tools.cpp \
		src/preprocessing.cpp
QMAKE_TARGET  = Phase_Shifting
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Phase_Shifting


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Phase_Shifting.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Phase_Shifting.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile Phase_Shifting.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Phase_Shifting.pro:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile Phase_Shifting.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/camera.h include/patterns.h include/phases.h include/tools.h include/preprocessing.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/camera.cpp src/patterns.cpp src/phases.cpp src/tools.cpp src/preprocessing.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: src/main.cpp include/camera.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/opencv.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/opencv_modules.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvdef.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/hal/interface.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cv_cpu_dispatch.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cv_cpu_helper.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/version.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/base.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvstd.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/ptr.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/neon_utils.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/vsx_utils.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/traits.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/matx.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/saturate.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/fast_math.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/mat.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/bufferpool.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/mat.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/persistence.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/operations.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvstd.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/utility.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/core_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/types_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/optim.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/ovx.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/calib3d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/features2d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/miniflann.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/defines.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/config.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/affine.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/calib3d/calib3d_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/flann_base.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/general.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/matrix.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/params.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/any.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/saving.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/nn_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/result_set.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/all_indices.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kdtree_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/dynamic_bitset.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/dist.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/heap.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/allocator.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/random.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kdtree_single_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kmeans_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/logger.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/composite_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/linear_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/hierarchical_clustering_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/lsh_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/lsh_table.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/autotuned_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/ground_truth.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/index_testing.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/timer.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/sampling.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/highgui.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgcodecs.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/highgui/highgui_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc/imgproc_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc/types_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgcodecs/imgcodecs_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio/videoio_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/ml.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect/detection_based_tracker.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect/objdetect_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/photo.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/photo/photo_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/emdL1.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/shape_transformer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/hist_cost.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/shape_distance.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/warpers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/warpers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda_types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/warpers_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/matchers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/xfeatures2d/cuda.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/motion_estimators.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/util.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/util_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/camera.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/exposure_compensate.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/seam_finders.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/blenders.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/superres.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/superres/optical_flow.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/tracking.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/background_segm.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/tracking_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/stabilizer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/global_motion.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/optical_flow.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/motion_core.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/outlier_rejection.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/motion_stabilizing.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/frame_source.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/log.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/inpainting.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/fast_marching.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/fast_marching_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/deblurring.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/wobble_suppression.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/ring_buffer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/widgets.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/viz3d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/vizcore.hpp \
		include/patterns.h \
		include/tools.h \
		include/phases.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

camera.o: src/camera.cpp /opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/opencv.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/opencv_modules.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvdef.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/hal/interface.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cv_cpu_dispatch.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cv_cpu_helper.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/version.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/base.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvstd.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/ptr.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/neon_utils.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/vsx_utils.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/traits.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/matx.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/saturate.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/fast_math.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/mat.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/bufferpool.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/mat.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/persistence.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/operations.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvstd.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/utility.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/core_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/types_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/optim.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/ovx.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/calib3d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/features2d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/miniflann.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/defines.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/config.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/affine.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/calib3d/calib3d_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/flann_base.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/general.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/matrix.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/params.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/any.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/saving.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/nn_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/result_set.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/all_indices.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kdtree_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/dynamic_bitset.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/dist.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/heap.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/allocator.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/random.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kdtree_single_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kmeans_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/logger.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/composite_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/linear_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/hierarchical_clustering_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/lsh_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/lsh_table.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/autotuned_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/ground_truth.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/index_testing.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/timer.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/sampling.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/highgui.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgcodecs.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/highgui/highgui_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc/imgproc_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc/types_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgcodecs/imgcodecs_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio/videoio_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/ml.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect/detection_based_tracker.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect/objdetect_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/photo.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/photo/photo_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/emdL1.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/shape_transformer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/hist_cost.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/shape_distance.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/warpers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/warpers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda_types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/warpers_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/matchers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/xfeatures2d/cuda.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/motion_estimators.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/util.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/util_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/camera.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/exposure_compensate.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/seam_finders.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/blenders.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/superres.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/superres/optical_flow.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/tracking.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/background_segm.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/tracking_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/stabilizer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/global_motion.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/optical_flow.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/motion_core.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/outlier_rejection.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/motion_stabilizing.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/frame_source.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/log.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/inpainting.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/fast_marching.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/fast_marching_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/deblurring.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/wobble_suppression.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/ring_buffer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/widgets.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/viz3d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/vizcore.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o src/camera.cpp

patterns.o: src/patterns.cpp /opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/opencv.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/opencv_modules.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvdef.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/hal/interface.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cv_cpu_dispatch.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cv_cpu_helper.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/version.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/base.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvstd.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/ptr.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/neon_utils.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/vsx_utils.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/traits.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/matx.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/saturate.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/fast_math.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/mat.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/bufferpool.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/mat.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/persistence.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/operations.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvstd.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/utility.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/core_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/types_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/optim.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/ovx.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/calib3d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/features2d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/miniflann.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/defines.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/config.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/affine.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/calib3d/calib3d_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/flann_base.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/general.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/matrix.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/params.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/any.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/saving.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/nn_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/result_set.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/all_indices.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kdtree_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/dynamic_bitset.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/dist.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/heap.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/allocator.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/random.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kdtree_single_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kmeans_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/logger.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/composite_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/linear_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/hierarchical_clustering_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/lsh_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/lsh_table.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/autotuned_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/ground_truth.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/index_testing.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/timer.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/sampling.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/highgui.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgcodecs.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/highgui/highgui_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc/imgproc_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc/types_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgcodecs/imgcodecs_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio/videoio_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/ml.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect/detection_based_tracker.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect/objdetect_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/photo.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/photo/photo_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/emdL1.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/shape_transformer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/hist_cost.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/shape_distance.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/warpers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/warpers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda_types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/warpers_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/matchers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/xfeatures2d/cuda.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/motion_estimators.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/util.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/util_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/camera.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/exposure_compensate.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/seam_finders.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/blenders.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/superres.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/superres/optical_flow.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/tracking.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/background_segm.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/tracking_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/stabilizer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/global_motion.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/optical_flow.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/motion_core.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/outlier_rejection.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/motion_stabilizing.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/frame_source.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/log.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/inpainting.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/fast_marching.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/fast_marching_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/deblurring.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/wobble_suppression.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/ring_buffer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/widgets.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/viz3d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/vizcore.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o patterns.o src/patterns.cpp

phases.o: src/phases.cpp /opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/opencv.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/opencv_modules.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvdef.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/hal/interface.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cv_cpu_dispatch.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cv_cpu_helper.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/version.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/base.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvstd.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/ptr.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/neon_utils.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/vsx_utils.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/traits.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/matx.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/saturate.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/fast_math.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/mat.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/bufferpool.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/mat.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/persistence.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/operations.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvstd.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/utility.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/core_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/types_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/optim.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/ovx.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/calib3d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/features2d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/miniflann.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/defines.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/config.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/affine.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/calib3d/calib3d_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/flann_base.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/general.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/matrix.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/params.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/any.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/saving.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/nn_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/result_set.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/all_indices.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kdtree_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/dynamic_bitset.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/dist.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/heap.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/allocator.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/random.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kdtree_single_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kmeans_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/logger.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/composite_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/linear_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/hierarchical_clustering_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/lsh_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/lsh_table.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/autotuned_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/ground_truth.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/index_testing.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/timer.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/sampling.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/highgui.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgcodecs.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/highgui/highgui_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc/imgproc_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc/types_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgcodecs/imgcodecs_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio/videoio_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/ml.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect/detection_based_tracker.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect/objdetect_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/photo.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/photo/photo_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/emdL1.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/shape_transformer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/hist_cost.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/shape_distance.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/warpers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/warpers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda_types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/warpers_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/matchers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/xfeatures2d/cuda.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/motion_estimators.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/util.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/util_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/camera.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/exposure_compensate.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/seam_finders.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/blenders.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/superres.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/superres/optical_flow.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/tracking.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/background_segm.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/tracking_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/stabilizer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/global_motion.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/optical_flow.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/motion_core.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/outlier_rejection.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/motion_stabilizing.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/frame_source.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/log.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/inpainting.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/fast_marching.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/fast_marching_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/deblurring.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/wobble_suppression.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/ring_buffer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/widgets.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/viz3d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/vizcore.hpp \
		include/tools.h \
		include/preprocessing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o phases.o src/phases.cpp

tools.o: src/tools.cpp /opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/opencv.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/opencv_modules.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvdef.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/hal/interface.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cv_cpu_dispatch.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cv_cpu_helper.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/version.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/base.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvstd.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/ptr.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/neon_utils.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/vsx_utils.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/traits.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/matx.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/saturate.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/fast_math.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/mat.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/bufferpool.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/mat.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/persistence.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/operations.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvstd.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/utility.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/core_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/types_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/optim.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/ovx.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/calib3d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/features2d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/miniflann.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/defines.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/config.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/affine.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/calib3d/calib3d_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/flann_base.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/general.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/matrix.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/params.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/any.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/saving.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/nn_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/result_set.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/all_indices.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kdtree_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/dynamic_bitset.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/dist.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/heap.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/allocator.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/random.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kdtree_single_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kmeans_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/logger.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/composite_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/linear_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/hierarchical_clustering_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/lsh_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/lsh_table.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/autotuned_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/ground_truth.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/index_testing.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/timer.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/sampling.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/highgui.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgcodecs.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/highgui/highgui_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc/imgproc_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc/types_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgcodecs/imgcodecs_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio/videoio_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/ml.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect/detection_based_tracker.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect/objdetect_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/photo.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/photo/photo_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/emdL1.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/shape_transformer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/hist_cost.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/shape_distance.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/warpers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/warpers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda_types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/warpers_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/matchers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/xfeatures2d/cuda.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/motion_estimators.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/util.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/util_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/camera.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/exposure_compensate.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/seam_finders.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/blenders.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/superres.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/superres/optical_flow.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/tracking.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/background_segm.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/tracking_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/stabilizer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/global_motion.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/optical_flow.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/motion_core.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/outlier_rejection.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/motion_stabilizing.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/frame_source.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/log.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/inpainting.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/fast_marching.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/fast_marching_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/deblurring.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/wobble_suppression.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/ring_buffer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/widgets.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/viz3d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/vizcore.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tools.o src/tools.cpp

preprocessing.o: src/preprocessing.cpp /opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/opencv.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/opencv_modules.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvdef.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/hal/interface.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cv_cpu_dispatch.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cv_cpu_helper.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/version.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/base.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvstd.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/ptr.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/neon_utils.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/vsx_utils.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/traits.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/matx.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/saturate.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/fast_math.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/mat.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/bufferpool.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/mat.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/persistence.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/operations.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cvstd.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/utility.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/core_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/types_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/optim.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/ovx.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/calib3d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/features2d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/miniflann.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/defines.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/config.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/affine.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/calib3d/calib3d_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/flann_base.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/general.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/matrix.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/params.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/any.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/saving.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/nn_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/result_set.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/all_indices.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kdtree_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/dynamic_bitset.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/dist.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/heap.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/allocator.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/random.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kdtree_single_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/kmeans_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/logger.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/composite_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/linear_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/hierarchical_clustering_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/lsh_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/lsh_table.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/autotuned_index.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/ground_truth.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/index_testing.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/timer.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/flann/sampling.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/highgui.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgcodecs.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/highgui/highgui_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc/imgproc_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc/types_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgcodecs/imgcodecs_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videoio/videoio_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/imgproc.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/ml.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect/detection_based_tracker.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/objdetect/objdetect_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/photo.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/photo/photo_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/emdL1.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/shape_transformer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/hist_cost.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/shape/shape_distance.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/warpers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/warpers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda_types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/cuda.inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/warpers_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/matchers.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/xfeatures2d/cuda.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/motion_estimators.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/util.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/util_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/camera.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/exposure_compensate.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/seam_finders.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/stitching/detail/blenders.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/superres.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/superres/optical_flow.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/tracking.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/background_segm.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/video/tracking_c.h \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/stabilizer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/global_motion.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/optical_flow.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/motion_core.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/outlier_rejection.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/motion_stabilizing.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/frame_source.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/log.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/inpainting.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/fast_marching.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/fast_marching_inl.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/deblurring.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/wobble_suppression.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/videostab/ring_buffer.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/types.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/widgets.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/viz3d.hpp \
		/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/viz/vizcore.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preprocessing.o src/preprocessing.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

